version: '3.7'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: chinenye/frontend
    ports:
    - target: 5000
      published: 5000
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    image: chinenye/backend
    ports:
    - target: 5001
      published: 5001
    depends_on:
      - database
  database:
    container_name: mysql-database
    build: ./database
    image: chinenye/database
    ports:
    - target: 3306
      published: 3306
    environment:
      - MYSQL_DATABASE=testdb
      - TEST_DATABASE_URI=mysql+pymysql://admin:admin123@mydatabase.ckmf2bglurlt.eu-west-2.rds.amazonaws.com:3306/testdb
      - SECRET_KEY=12345
      - MYSQL_ROOT_PASSWORD=admin123
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./Nginx/nginx.conf
      target: /etc/nginx/nginx.conf
