version: '3.7'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: chinenye/frontend
    ports:
    - target: 5000
    published: 5000
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    image: chinenye/backend
    ports:
    - target: 5001
    published: 5001
    depends_on:
      - database
  database:
    container_name: mysql-database
    build: ./database
    image: chinenye/database
    ports:
    - target: 3306
    published: 3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TEST_DATABASE_URI=${TEST_DATABASE_URI}
      - DATABASE_URI=${DB_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
  
