version: '3.7'
services:
  frontend:
    container_name: frontend
    image: chinenye/frontend
    build: ./frontend
    depends_on:
      - backend
  backend:
    container_name: backend
    image: chinenye/backend
    build: ./backend
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mysql
  mysql:
    container_name: mysql-database
    build: ./database
    image: chinenye/database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
