version: '3.7'
services:
  frontend:
    image: chinenye/frontend
    build: ./frontend/
    depends_on:
      - backend
  backend:
    image: backend
    build: ./backend/
    depends_on:
      - database
  database:
    build: ./database
    environment:
      - DATABASE_URI=${DB_URI}
      - SECRET_KEY=$(SECRET_KEY)
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  
